services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
    environment:
      - FLASK_APP=run:app
      - FLASK_DEBUG=1